config/routes.rb
Myfinn::Application.routes.draw do
  devise_for :users

  root :to => 'insertions#index'

  get 'insertions/' => 'insertions#index'
  get 'insertions/archive' => 'insertions#archive'
  get 'insertions/:id/hide' => 'insertions#hide'
  get 'insertions/hide_all' => 'insertions#hide_all'
  get 'insertions/:id/promote' => 'insertions#promote'

  post 'apartments/create' => 'apartments#create'
  get 'apartments/' => 'apartments#index'
  get 'apartments/:id' => 'apartments#show'
  get 'apartments/delete/:id' => 'apartments#delete'
  post 'apartments/:id/rating' => 'apartments#rating'
  post 'apartments/:id/status' => 'apartments#status'

  get 'apartments/:id/appointment' => 'appointments#show'
  post 'appointments/:id' => 'appointments#update'

  get 'comments/:id' => 'comments#show'
  post 'comments' => 'comments#save'
  post 'comments/delete' => 'comments#delete'

  get 'calendar/' => 'calendar#index'
  get 'calendar/events' => 'calendar#events'

  post 'filter/update' => 'filter#update'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || SITE_NAME %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background:#eee">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">MyFinn</a>
        <% if current_user %>
          <ul class="nav">
            <li><%= link_to "New insertions", insertions_path %></li>
            <li><%= link_to "Apartments", apartments_path %></li>
            <li><%= link_to "Calendar", calendar_path %></li>
            <li class="divider-vertical" />
            <%= render :partial => "create" %>
          </ul>
          <p class="navbar-text pull-right">
          Welcome, <%= current_user.name %>! <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
          </p>
      <% end %>
      </div>
    </div>
  </div>

  <div class="container">
<%= yield %>
  </div> 
</body>
</html>